version: '3.8'


services:

  api-gateway:
    build: ./services/api-gateway
    container_name: prost-o-projekt-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      # Mapujemy kod bramy (tak jak było)
      - ./services/api-gateway:/app
      - /app/node_modules
      # NOWE MAPOWANIE: Udostępnij folder ze specyfikacjami wewnątrz kontenera
      - ./api-specs:/app/specs 
    depends_on:
      - legacy-monolith
      - project-service
      - user-service

  # Zmieniamy nazwę serwisu na bardziej opisową
  legacy-monolith:
    # ZMIANA: Podajemy kontekst budowania
    build: ./services/legacy-monolith
    container_name: prost-o-projekt-monolith
    # ports:
    #   - "3000:3000"
    volumes:
      - ./services/legacy-monolith:/app
      - /app/node_modules
    depends_on:
      - legacy-db
    environment:
      - DB_HOST=legacy-db
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=prostoprojekt
      - DB_PORT=5432
      - PORT=3000


  # Zmieniamy nazwę serwisu bazy danych
  legacy-db:
    image: postgres:14
    container_name: prost-o-projekt-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=prostoprojekt
    volumes:
      - legacy-db-data:/var/lib/postgresql/data

  project-service:
    build: ./services/project-service
    container_name: prost-o-projekt-project-service
    restart: always
    volumes:
      - ./services/project-service:/app
      - /app/node_modules
    depends_on:
      - project-db
    environment:
      - DB_HOST=project-db
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=projects_db
      - PORT=3000
  
  project-db:
    image: postgres:14
    container_name: prost-o-projekt-project-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=projects_db
    volumes:
      - project-db-data:/var/lib/postgresql/data


  user-service:
    build: ./services/user-service
    container_name: prost-o-projekt-user-service
    restart: always
    volumes:
      - ./services/user-service:/app
    env_file:
      - ./.env
    environment:
      - MONGO_URI=mongodb://admin:secret@user-db:27017/
      - RABBITMQ_HOST=rabbitmq # Nowa zmienna środowiskowa
    depends_on:
      - user-db
      - rabbitmq 

  user-db:
    image: mongo:5.0
    container_name: prost-o-projekt-user-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - user-db-data:/data/db

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: prost-o-projekt-swagger-ui
    ports:
      - "8080:8080"
    environment:
      # Podaj adres URL do specyfikacji, którą Swagger ma wczytać przy starcie
      - URL=http://api-gateway:3000/specs/project-service-api.yaml
    depends_on:
      - api-gateway

  rabbitmq:
    image: rabbitmq:3.11-management-alpine # Używamy lekkiej wersji z panelem
    container_name: prost-o-projekt-rabbitmq
    ports:
      - "5672:5672"  # Port protokołu AMQP, do komunikacji z aplikacjami
      - "15672:15672" # Port panelu webowego do zarządzania
    environment:
      # Domyślne dane logowania, wystarczające na development
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  notification-service:
    build:
      context: ./services/notification-service
    container_name: prost-o-projekt-notification-service
    restart: always
    depends_on:
      - rabbitmq


volumes:
  legacy-db-data:
  project-db-data:
  user-db-data:
